<?php

namespace App\Repositories;

use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use App\Repositories\sms_idRepository;
use App\Models\SmsId;
use App\Validators\SmsIdValidator;

/**
 * Class SmsIdRepositoryEloquent.
 *
 * @package namespace App\Repositories;
 */
class SmsIdRepositoryEloquent extends BaseRepository implements SmsIdRepository
{
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return SmsId::class;
    }

    

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }

    public function create(array $attributes)
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }

}
